In [8]:
import numpy as np
from numpy import linalg as LA

In [9]:
cifar10_mean = np.array((0.4914, 0.4822, 0.4465))
cifar10_std = np.array((0.2471, 0.2435, 0.2616))

- 3 values
- distance group
  - 0.5
  - 0.6
  - 0.65
- 2 sets
  - with Std
  - Without std

In [10]:
# generate 100 random unit vector dimension
sample_num = 100
rng = np.random.default_rng(seed=42)
rnd_unit_vector_list = []
rnd_vectors = np.round(2 * rng.random((sample_num, 3)) - 1, decimals=3)
for i in range(rnd_vectors.shape[0]):
    unit_vector = rnd_vectors[i] / LA.norm(rnd_vectors[i], 2)
    rnd_unit_vector_list.append(unit_vector)

In [11]:
print(rnd_unit_vector_list[0])
print(np.amax(rnd_unit_vector_list[0]))

[ 0.6017703  -0.13397076  0.78735274]
0.7873527441595458


In [12]:
# filter in range (0, 1) with factor 0.7
factor = 0.7
filtered_rnd_unit_vector_list = []

for unit_vector in rnd_unit_vector_list:
    result_vector = cifar10_mean + (unit_vector * factor)
    min_val = np.amin(result_vector)
    max_val = np.amax(result_vector)
    if (min_val > 0) and (max_val < 1):
        # print(result_vector)
        # print(LA.norm(result_vector - cifar10_mean, 2))
        filtered_rnd_unit_vector_list.append(unit_vector)


In [17]:
for i in range(3):
    selected_unit_vector = filtered_rnd_unit_vector_list[i]
    print(np.round(selected_unit_vector, 3))

[ 0.602 -0.134  0.787]
[ 0.301 -0.619  0.725]
[ 0.465 -0.435  0.771]


In [13]:
# prepare exp mean values
exp_mean_list = []
unit_factor_list = [0.5, 0.6, 0.7]

for i in range(3):
    selected_unit_vector = filtered_rnd_unit_vector_list[i]
    for unit_factor in unit_factor_list:
        mod_result_mean = np.round(cifar10_mean + (selected_unit_vector * unit_factor), 3)
        exp_mean_list.append(mod_result_mean)

In [14]:
for exp_mean in exp_mean_list:
    print(exp_mean)
    # print(LA.norm(exp_mean - cifar10_mean, 2))

[0.792 0.415 0.84 ]
[0.852 0.402 0.919]
[0.913 0.388 0.998]
[0.642 0.173 0.809]
[0.672 0.111 0.882]
[0.702 0.049 0.954]
[0.724 0.265 0.832]
[0.77  0.221 0.909]
[0.817 0.178 0.986]
