In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
cifar10_mean = np.array((0.4914, 0.4822, 0.4465))
cifar10_std = np.array((0.2471, 0.2435, 0.2616))

In [3]:
print(LA.norm(cifar10_mean, 2))

0.8205809222739705


Mean:
- +-0.1
- +-0.2
- +-0.3

Direction:
- ++-
- +-+
- -++

Std:
- +0.1
- +0.05
- +0.025
- -0.1
- -0.05
- -0.025

In [4]:
rng = np.random.default_rng(seed=42)
rnd_mean_list = np.round(rng.random((6, 3)), decimals=3)
print(rnd_mean_list)

[[0.774 0.439 0.859]
 [0.697 0.094 0.976]
 [0.761 0.786 0.128]
 [0.45  0.371 0.927]
 [0.644 0.823 0.443]
 [0.227 0.555 0.064]]


In [5]:
print(cifar10_std + 0.1)
print(cifar10_std + 0.05)
print(cifar10_std + 0.025)
print(cifar10_std - 0.1)
print(cifar10_std - 0.05)
print(cifar10_std - 0.025)

[0.3471 0.3435 0.3616]
[0.2971 0.2935 0.3116]
[0.2721 0.2685 0.2866]
[0.1471 0.1435 0.1616]
[0.1971 0.1935 0.2116]
[0.2221 0.2185 0.2366]


In [6]:
unit_vec = rnd_mean_list[0] / LA.norm(rnd_mean_list[0], 2)
print(unit_vec)
print(LA.norm(unit_vec))

[0.62580777 0.35494782 0.69453343]
0.9999999999999999


In [7]:
for i in range(rnd_mean_list.shape[0]):
    print(LA.norm(rnd_mean_list[i] - cifar10_mean, 2))

0.5018817091705973
0.6879977107520053
0.5161597136546012
0.494933985497056
0.3734215446382278
0.47065215393111715


In [8]:
print(str([1, 2, 3]).replace(' ', '').replace(',', '_')[1:-1])

1_2_3
