In [1]:
import numpy as np
from numpy import linalg as LA
from pprint import pprint

In [2]:
cifar10_mean = np.array((0.4914, 0.4822, 0.4465))
cifar10_std = np.array((0.2471, 0.2435, 0.2616))

- Select 10 uniform random vector

In [10]:
def cosine_similarity(A: np.ndarray, B: np.ndarray):
    assert A.shape == B.shape
    return np.dot(A, B) / (LA.norm(A, 2) * LA.norm(B, 2))

In [19]:
sample_num = 10
rng: np.random._generator.Generator = np.random.default_rng(seed=123)
rnd_vectors = rng.uniform(-1, 1, size=(sample_num, 3))
filtered_rnd_vector_list = []
for i in range(sample_num):
    filtered_rnd_vector_list.append(np.round(rnd_vectors[i], 3))



In [23]:
# check value
for rnd_vector in filtered_rnd_vector_list:
    print(rnd_vector)

[ 0.365 -0.892 -0.559]
[-0.631 -0.648  0.624]
[ 0.847 -0.447  0.64 ]
[ 0.78   0.026 -0.51 ]
[ 0.648 -0.572  0.483]
[ 0.26   0.855 -0.536]
[ 0.598  0.036 -0.537]
[-0.668 -0.004  0.165]
[-0.631 -0.97  -0.058]
[0.456 0.837 0.251]


In [21]:
# check cosine similarity
for rnd_vector in filtered_rnd_vector_list:
    # print(rnd_vector)
    print(cosine_similarity(rnd_vector, cifar10_mean))

-0.5472756413221266
-0.38142297152190263
0.514630357634909
0.21975011929153412
0.3178726270006958
0.3516764001216642
0.10822148569671865
-0.45429868991995137
-0.8453370703808512
0.9146218612514739


In [22]:
# check magnitude
for rnd_vector in filtered_rnd_vector_list:
    print(LA.norm(rnd_vector, 2))

1.1141678509093682
1.0988362025342995
1.151875861367014
0.9322960903060787
0.9901398891065848
1.0420753331693442
0.8045302977514271
0.6880879304275
1.1586306572847103
0.9856500393141574


- Select 1 unit vector which can have 0.95 dist from 100 sample

In [3]:
# generate 100 random unit vector dimension
sample_num = 100000
rng: np.random._generator.Generator = np.random.default_rng(seed=42)
rnd_vectors = rng.uniform(-1, 1, size=(sample_num, 3))

rnd_unit_vector_list = []
for i in range(rnd_vectors.shape[0]):
    unit_vector = rnd_vectors[i] / LA.norm(rnd_vectors[i], 2)
    rnd_unit_vector_list.append(unit_vector)


In [4]:
# filter in range (0, 1) with factor 0.9
factor = 0.9
filtered_rnd_unit_vector_list = []

for unit_vector in rnd_unit_vector_list:
    result_vector = cifar10_mean + (unit_vector * factor)
    min_val = np.amin(result_vector)
    max_val = np.amax(result_vector)
    if (min_val > 0) and (max_val < 1):
        # print(result_vector)
        # print(LA.norm(result_vector - cifar10_mean, 2))
        filtered_rnd_unit_vector_list.append(unit_vector)

In [5]:
pprint(filtered_rnd_unit_vector_list)

[array([0.55976816, 0.56755369, 0.60377348]),
 array([0.55284315, 0.56556923, 0.6119607 ]),
 array([0.54919051, 0.5691553 , 0.61192485]),
 array([0.56200524, 0.55707775, 0.61140371]),
 array([0.56362358, 0.55371656, 0.61296527]),
 array([0.55862862, 0.57493787, 0.5978131 ])]


In [10]:
print(np.round(filtered_rnd_unit_vector_list[0], 3))

[0.56  0.568 0.604]


In [6]:
# test generated unit vector
result_vector = cifar10_mean + (filtered_rnd_unit_vector_list[0] * factor)
print(result_vector)

print(LA.norm(cifar10_mean + (filtered_rnd_unit_vector_list[0] * factor) - cifar10_mean, 2))

[0.99519134 0.99299832 0.98989613]
0.9


In [7]:
# prepare exp mean values
exp_mean_list = []
unit_factor_list = [
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.55,
    0.6,
    0.65,
    0.7,
    0.75,
    0.8,
    0.85,
    0.9,
]

selected_unit_vector = filtered_rnd_unit_vector_list[0]
for unit_factor in unit_factor_list:
    mod_result_mean = np.round(cifar10_mean + (selected_unit_vector * unit_factor), 3)
    exp_mean_list.append(mod_result_mean)


In [8]:
for exp_mean in exp_mean_list:
    print(exp_mean)
    # print(LA.norm(exp_mean - cifar10_mean, 2))

[0.547 0.539 0.507]
[0.603 0.596 0.567]
[0.659 0.652 0.628]
[0.715 0.709 0.688]
[0.771 0.766 0.748]
[0.799 0.794 0.779]
[0.827 0.823 0.809]
[0.855 0.851 0.839]
[0.883 0.879 0.869]
[0.911 0.908 0.899]
[0.939 0.936 0.93 ]
[0.967 0.965 0.96 ]
[0.995 0.993 0.99 ]


In [9]:
# get opposite unit vector of default mean
cifar10_mean_unit_vector = cifar10_mean / LA.norm(cifar10_mean, 2)
opp_cifar10_mean_unit_vector = - cifar10_mean_unit_vector
print(opp_cifar10_mean_unit_vector)
_factor = 0.9
result_vector = cifar10_mean + (opp_cifar10_mean_unit_vector * _factor)
print(result_vector)

print(LA.norm(cifar10_mean + (opp_cifar10_mean_unit_vector * _factor) - cifar10_mean, 2))

[-0.59884405 -0.58763248 -0.54412671]
[-0.04755964 -0.04666923 -0.04321404]
0.9
